dist: xenial
language: python
cache: pip

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

env:
  - DJANGO="django>=2.2,<3.3"
before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install jslint -g
  - jslint django_netjsongraph/static/netjsongraph/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - coverage run --source=django_netjsongraph runtests.py
  - ./tests/manage.py makemigrations django_netjsongraph --dry-run | grep "No changes detected";
  - openwisp-utils-qa-checks --migration-path "./django_netjsongraph/migrations"

after_success:
  coveralls
